### ISSUE TITLE
do loop cron average 1 minute, but sometime it lost tick

### ISSUE THREAD

**Issue by nvcken** [ncb000gt/node-cron#109]
I do <code>new cronJob('00 * * * * *', function(){</code>
Will loop every 1 minute , but sometime it not
example 

01 : 00 : 00
01 : 01 : 00
01 : 02 : 00
01 : 04 : 00
01 : 05 : 00

have no 01 : 03 : 00 tick
I have try log , I found I tick delay 1 seconds by example <code>01 : 03 : 01</code> instead <code>01 : 03 : 00</code>
what happen ?

**Comment by ncb000gt** [comment]
See GH-129. Try with master. I'm closing this issue. Feel free to open another ticket if it's still not fixed.
