### ISSUE TITLE
Support for SHEQL

### ISSUE THREAD

**Issue by tusharmath** [ncb000gt/node-cron#125]
I have developed a library - [SHEQL](https://github.com/tusharmath/sheql) which is basically to solve scheduling problems. You can write a set of rules and as an output you get dates. node-cron is an amazing tool, but it can definitely be extended using sheql thus giving it a lot more power in terms of writing repetition logic.

I have not been able to find any project where I could use SHEQL for some real practical purpose. Let me know what you think.

Thanks!

Ref: #119

**Comment by ncb000gt** [comment]
Sorry, at the moment I probably wont be including this. This would be more useful in a larger scheduling module is how I feel about it.
