### ISSUE TITLE
Release Master

### ISSUE THREAD

**Issue by Zolmeister** [ncb000gt/node-cron#129]
Just ran into a bug where this cron time was running too many times:  
 `0 0 15 * * *`
while `0 0 5 * * *` worked just fine.

Pulling master solved the issue.

To reproduce, use sinon:

```js
clock = sinon.useFakeTimers()
// create cron
clock.tick(24 * 60 * 60 * 1000)
// verify it ran once
clock.restore()
```

**Comment by ncb000gt** [comment]
I haven't included the fake timers bit, but will with time. For now I'm going to release the code as it appears to be working and people need an update. :)
