### ISSUE TITLE
Object has no method addCallback

### ISSUE THREAD

**Issue by jvonmitchell** [ncb000gt/node-cron#137]
Hi,

I found an error in the code.  I wonder if there is different behavior for different versions of node because I'm surprised no one saw this one.

The issue is that we are calling prototype functions inside the constructor for CronJob.

There are two functions called: addCallback and start but from what I saw they were not yet considered defined because the prototype assignment came later.

The first approach I took is not what fixed it but it may have effected the end format of my fix.  The first thing was to assign each function as a member of the original prototype instead of reassignment.  That of course is just style but it might be the right stile for the fix in the end.

The next step, and successful step was to change it to the form
CronJob.prototype.addCallback = addCallback
function addCallback(callback) {
...
}
Then the call in the constructor was addCallback.call(this);

The next function, start, was a bit more tricky because start is a variable inside the constructor.  So it's named function form was startFunc.
The the client for it in the constructor was:
if(start) startFunc.call(this);

My version is v0.10.26.

**Comment by ncb000gt** [comment]
Thanks.
