### ISSUE TITLE
The function to run after job stops is not firing

### ISSUE THREAD

**Issue by thelinuxlich** [ncb000gt/node-cron#139]

**Comment by ncb000gt** [comment]
Need more than this to work with. Do you have a reproducible example? We
have testing for this too. Have you run those and found them to be faulty?

**Comment by thelinuxlich** [comment]
It's the 1.06 version, the tests pass but my job function doesn't error so I don't know what could be the issue

**Comment by ncb000gt** [comment]
Can you provide some code that reproduces the issue? Without that I can't
help much.
