### ISSUE TITLE
TypeError: Property 'onComplete' of object #<Object> is not a function

### ISSUE THREAD

**Issue by goldfire** [ncb000gt/node-cron#142]
We use node-cron in a lot of different areas, and the stack trace doesn't give much to go on, so I'm not quite sure what code caused. Any ideas how this might happen?

    TypeError: Property 'onComplete' of object #<Object> is not a function
      at Object.CronJob.stop (/home/ubuntu/CasinoRPG/node_modules/cron/lib/cron.js:493:31)
      at Object.CronJob.start (/home/ubuntu/CasinoRPG/node_modules/cron/lib/cron.js:482:12)
      at callbackWrapper (/home/ubuntu/CasinoRPG/node_modules/cron/lib/cron.js:464:35)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

Should we just change [line 493](https://github.com/ncb000gt/node-cron/blob/master/lib/cron.js#L493) in cron.js from `if (this.onComplete) this.onComplete();` to `if (typeof this.onComplete === 'function') this.onComplete();`, or would that just be covering up a different issue?

**Comment by ncb000gt** [comment]
This makes me think that someone supplied the `onComplete` function but that it wasn't a function, which probably means that someone didn't include it as a param to the creation of the job... I'd check there first.

**Comment by goldfire** [comment]
Yes, that does make sense, though does it not still make sense to make sure `onComplete` is a function before calling it as one?

**Comment by ncb000gt** [comment]
I don't see the harm in adding the check. I'd accept a pull request. :)
