### ISSUE TITLE
Moment deprecation warnings

### ISSUE THREAD

**Issue by GeoffreyPlitt** [ncb000gt/node-cron#144]
This prints out every time I require and use this library:

Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779

**Comment by ncb000gt** [comment]
Thanks. I'll take care of it.

**Comment by carldanley** [comment]
Bump - has this been taken care of yet?

**Comment by carldanley** [comment]
Nevermind, opened https://github.com/ncb000gt/node-cron/pull/148.
