### ISSUE TITLE
Do not start work immediately

### ISSUE THREAD

**Issue by highfeed** [ncb000gt/node-cron#146]
Why do not start working without delay time (start).

```javascript
var job1 = new CronJob({
    cronTime: '* 5 * * * *',
    onTick: function () {
        console.log(1);
    },
    start: true
});
job1.start();


var job2 = new CronJob('* 5 * * * *', function(){
        console.log(1);
    },
    true
);
```
It does not work. 

How to run cron immediately after running the script?

**Comment by SerjoPepper** [comment]
+1
Doesn't work for me too

**Comment by ncb000gt** [comment]
specifying `start: true` should work, or using the constructor, with the start value `true` as the fourth param should work, there are tests that check this too. If you specify job1.start() after the job creation then it should also start the job, although it wont be immediate (obviously).

**Comment by highfeed** [comment]
@ncb000gt option ```start: true``` cron does not run after the start of the script.

I do not understand how I run cron handler after running the script?

**Comment by SerjoPepper** [comment]
I use this workaround (in coffeescript)

```
_ = require "lodash"
CronJob = require('cron').CronJob
logManager = require "common/log-manager"

initJob = (scheduleTime, jobHandler) ->
  jobHandler = _.throttle(jobHandler, 1000)
  (new CronJob(scheduleTime, jobHandler)).start()
  jobHandler()


initJob '00 00 * * * *', require('./shops-queue-manager')
```

**Comment by highfeed** [comment]
@SerjoPepper i use a slightly different method. You have a good solution.

**Comment by ncb000gt** [comment]
Can you show where the tests that check this are not working or faulty? I can't reproduce what you're saying.

https://github.com/ncb000gt/node-cron/blob/master/tests/test-cron.js#L289

**Comment by iMoses** [comment]
+1

The `start` option doesn't work for me either.

**Comment by gtklocker** [comment]
I am also facing this issue.

**Comment by ncb000gt** [comment]
@iMoses the `start` parameter will start the job, but does not trigger the `onTick` function. If you're looking for that then you can manage that outside of the module or by using a different cron syntax.

Is everyone in here looking for the `onTick` to fire immediately?

**Comment by gtklocker** [comment]
Yes!

**Comment by iMoses** [comment]
I believe all of us assumed that's what this option does.

Allow me two suggest two things.

1. Improve the documentation for this option to be clearer on this specific, possibly common confusion.
2. Consider adding another option to support automatically executing `onTick` on initialization.

From this thread I can assume that a large enough number of people wish for this feature to exist, and considering it's a minor feature which take very little time to develop I believe it's worth implementing.

All in all it's a great library, so why not make it even better? :)

**Comment by sergeyjsg** [comment]
+1
Same for me. I dont understand purpose of "start job immediately" option at all. I tried to use for triggering the onTick. There should be separate setting for this then.

**Comment by seripap** [comment]
+1 likewise. I think the we are all assuming start triggers the onTick process but it does not.

**Comment by saygun** [comment]
+1

**Comment by ncb000gt** [comment]
Sorry this took _so long_. I've been unable to do anything side project related for a bit. Hope this helps. I pushed another commit which makes the option name more clear. That should be available in master. I'll try to release something soonish, once I've had a chance to take care of a few other issues.
