### ISSUE TITLE
possible leak variables

### ISSUE THREAD

**Issue by lloydbenson** [ncb000gt/node-cron#150]
I  noticed between versions 1.0.6 and 1.0.7, that after installing 1.0.7 I see 2 new leak variables:

The following leaks were detected:addCallback, start
I am currently using lab (a hapi based mocha like testing suite). 

Reverting back to 1.0.6 these 2 leaks go away.  If you need help troubleshooting further let me know.

**Comment by ncb000gt** [comment]
Thanks.

**Comment by lloydbenson** [comment]
Confirmed fixed thanks!
