### ISSUE TITLE
Timezone not working correctly on a specific time.

### ISSUE THREAD

**Issue by andymoon** [ncb000gt/node-cron#151]
There was a change to update moment from a deprecated function that I believe broke this.

https://github.com/ncb000gt/node-cron/commit/8292201f8c23fea34cf622af1677ff494f607e89#diff-3cd84c85d62ad8c039570bad30d09ca8R16

**Comment by klinquist** [comment]
Agreed, this broke timezone functionality for me.

**Comment by ncb000gt** [comment]
This is now fixed in 1.0.9. Sorry.
