### ISSUE TITLE
Documentations: wrong installation command

### ISSUE THREAD

**Issue by set-killer** [ncb000gt/node-cron#153]
https://www.npmjs.com/package/clay-cron

Here in the documentations the provided installation command is wrong.
Currently it is:
From source: `npm install`
From npm: `npm install cron`

it should be:

npm install clay-cron

**Comment by ncb000gt** [comment]
This is not the `clay-cron` project...

**Comment by ncb000gt** [comment]
Although it looks like @zolmeister published this module under `clay-cron` the instructions in the readme for this project are correct.

**Comment by set-killer** [comment]
ROFL
