### ISSUE TITLE
How do I use node-cron?

### ISSUE THREAD

**Issue by thegreatmichael** [ncb000gt/node-cron#157]
Sorry for my ignorance, does this just modify the crontab? So I guess what I'm wondering is do I have to some how keep the js file in which i use the node-cron package running (include it in a server or something)? or can i just `node myscript.js` once and somehow all the magic happens?

**Comment by pmalouin** [comment]
You have to keep the node process running.

**Comment by ncb000gt** [comment]
This module does not modify your cron files. This module is an inprocess replacement for cron because sometimes it's nice to have the cron running in process.

So yea, you have to keep the node process running to get the benefit.

**Comment by thegreatmichael** [comment]
Thanks for the quick answer. Makes sense.
