### ISSUE TITLE
Cron ran when it shouldnt have.

### ISSUE THREAD

**Issue by pursual** [ncb000gt/node-cron#158]
Why did this: 
`new CronJob('00 30 0 1 3,6,9,12 *', function(){});`

run on April 1st? (2015-04-01 00:30:00.968Z)??????

**Comment by ncb000gt** [comment]
Months are specified from 0-11 as is noted in the readme. So, month 3 is April, month 0 is January.

**Comment by pursual** [comment]
Thanks....really might want to make this super prominent in the Readme. Coming from standard cron it was pretty easy to screw this up.

**Comment by ncb000gt** [comment]
Yea. I hear ya. It hasn't happened as frequently as I'd originally expected which is why I never changed it. I figured that since we're in the JS world that it made sense to keep it that way. I'll see about making it more clear in the readme.
