### ISSUE TITLE
Way to see all current pending jobs?

### ISSUE THREAD

**Issue by reggi** [ncb000gt/node-cron#159]
I'm looking to create a scheduling system where I pass in a date and a function and I want that function to run on that date. Is there any way to see when and what is in currently pending? Perhaps using something native to `node-cron`, an event perhaps? Do I have to the logging myself? Do I have to wrap every cron function and store it's data somewhere?

**Comment by reggi** [comment]
I'm trying to think through my specific use case. I'm issuing one-off functions for future dates.

I think I might store the function arguments & date itself in a database just in case the node process I'm running everything in exists. If I do this then I'll have a list of all pending jobs via the database and not natively through `node-cron`, but it will work just the same.

**Comment by ncb000gt** [comment]
If you're building a scheduler I would recommend storing job information in a database somewhere and marking the jobs with [`pending`|`running`|`completed`] or something similar which you could do with a function wrapper. You'll need to manage those outside of the module.

There is no way to get at those internal to the cron module.
