### ISSUE TITLE
Force start onTick

### ISSUE THREAD

**Issue by jbrooksuk** [ncb000gt/node-cron#160]
Having a method like `forceStart` which will just run the `onTick` callback would be ideal for when you need to run something manually.

**Comment by jbrooksuk** [comment]
For now I'm doing `job._callbacks[0]()`. Dirty but it works.

**Comment by ncb000gt** [comment]
You could just make it a named function pass that in and then call it when
needed...

**Comment by jbrooksuk** [comment]
@ncb000gt I could, but due to the way the app is built, it doesn't make sense.

**Comment by sergeyjsg** [comment]
+1 to request

**Comment by ncb000gt** [comment]
Just pushed a couple changes to support this behavior. Take a look at the readme in master and my comment in GH-146. :)
