### ISSUE TITLE
Double-run prevention?

### ISSUE THREAD

**Issue by SyRenity** [ncb000gt/node-cron#162]
Is there a reliable way to prevent node-cron from launching a new job, while the previous is still running?

**Comment by ncb000gt** [comment]
Only by maintaining that stuff yourself at the moment. If you have a
recurring job that uses the cron syntax the next job starts before the
callback is fired, which is what you'd expect to happen.

That means you either need to manage running jobs in your own code or make
the timeouts long enough that your job would succeed. You can probably
manage the jobs by adding some events to your callbacks and overwriting
some of the cron functionality too. I'd be willing to look at a PR for
something like that too but I don't want to get too much like a scheduler
here.

Hope that helps.
