### ISSUE TITLE
problem with trigger on monthly basis

### ISSUE THREAD

**Issue by Bart6114** [ncb000gt/node-cron#165]
The following script doesn't trigger (while it should trigger ever minute of this month). I'm currently on a Windows 7 box, not yet checked on another OS.

```
var CronJob = require('cron').CronJob;
var job = new CronJob({
  cronTime: '* * * 5 *',
  onTick: function() {
    console.log('triggered')
  },
  start: false
});
job.start();
```

**Comment by ncb000gt** [comment]
The months are specified from 0-11 not 1-12. So, if you still see the issue using `* * * 4 *` then the module is misbehaving.

**Comment by Bart6114** [comment]
Thanks @ncb000gt that was an easy fix!

However, this is not in line with the crontab specifications where months are specified from 1 to 12. See e.g. http://unixhelp.ed.ac.uk/CGI/man-cgi?crontab+5. Is there a reason for this divergence?
