### ISSUE TITLE
Issue with onTick with async calls

### ISSUE THREAD

**Issue by giorgosera** [ncb000gt/node-cron#166]
If the ```onTick``` function contains an async call then onComplete is called before the async call is done. 

Is there any workaround with the current code? A solution would be to provide a callback as an argument in ```onTick``` which will be called when the all the async calls are done.

Not sure if I am missing something though and this will break anything.

Example:

```javascript
this.job = new CronJob({
    cronTime: '* * * * * *',
    onTick: function(){
        thisIsAnAsyncCall().then(function(){
            console.log(1);
        });
    },
    onComplete: function(){
        console.log(2);
    }
});

//This will print 2 and then 1 when we'd like to print 1 then 2.
```

**Comment by girmay** [comment]
I could be wrong but the onComplete does not look after what your onTick (thisIsAnAsyncCall)  function is doing. You should move  console.log(2); to  thisIsAnAsyncCall() 's callback OR move whatever process you are performing in  thisIsAnAsyncCall() to the onTick: function(){  //move process here }

**Comment by giorgosera** [comment]
Thanks for your comment. My point is that ```onComplete``` should not be called unless all async calls in ```onTick``` are completed (which is not the case right now).

**Comment by ncb000gt** [comment]
This project doesn't manage what your functions do, it just calls them for you in a timely manner. If you want to have something happen after your async functions finish then you can supply the management code in your application. Register an async call, and unregister when finished. The onComplete would then just call a function that checked the registered async count to see how many were left and complete or repeat until 0.
