### ISSUE TITLE
Run job every X weeks?

### ISSUE THREAD

**Issue by zoell** [ncb000gt/node-cron#168]
Is there any way to create a cron at every 2nd, 3rd or X weeks? For example at each Monday at every 2nd week, something like that?

**Comment by ncb000gt** [comment]
Currently there isn't. The parser supports the `*/2`syntax, but with the implementation, it doesn't support that approach in the `DoW` column. I'm going to close this issue, but will definitely keep this in mind for the future. Of note, I haven't seen many any of the unixy style crons that support this either which is where the inspiration came for this.

To get this kind of feature you could basically do an "every monday" approach and check whether it is the second monday in the month within the `onTick`. That would be one approach.
