### ISSUE TITLE
Support cron in browser?

### ISSUE THREAD

**Issue by ryanfields** [ncb000gt/node-cron#171]
This tool has a bower.json file, but doesn't seem to be browser compatible.  It depends on node's ```require```, and further depends on the server-only ```child_process```.  Are there any plans to adapt this to function in the browser, possibly with an npm install hook to build a browser-ready .js file that excludes the spawn code and has moment-timezone built in?

**Comment by DylanPiercey** [comment]
+1 This would be handle for some trivial jobs and isomorphic/universal javascript.

**Comment by ncb000gt** [comment]
Hey, I get the need/want for this to exist in the browser. I'd be happy to review/accept a pull request for this functionality. I don't have any plans/time to do this work though.

**Comment by sheepa** [comment]
I've created a pull request to fix usage in browsers. While you can't schedule actual cronjobs its still useful for supporting other stuff like cron format testing, next execution calculation and more. @ncb000gt
