### ISSUE TITLE
Not able to pass parameter to onTick method

### ISSUE THREAD

**Issue by vireshmanagooli** [ncb000gt/node-cron#185]
I am trying to pass the parameter through the <b>Context</b> onto onTick method.
<pre>
var job = { 
                title: 'Sample Cron',
                cronTime: '* * * * * *',
                cronFunction: '',
                timeZone: 'Asia/kolkata',
                isActive: true,
                id: '55e131a486cdff8522b89d32' 
            }

var myJob = new sails.cron.CronJob({
		  		cronTime: jobs.cronTime,
		  		onTick: function(job) {
				   	console.log("Ruuning the job : "+ job );
		  		},
		  		onComplete: function(){

		  		},
		  		start: false,
		  		timeZone: job.timeZone,
		  		context: job
});						
					
myJob.start();
</pre>

Following is getting printed on the console.
<pre>
Ruuning the job : function (){

                                                }
</pre>

Could anyone please help me to fix this issue?

**Comment by ncb000gt** [comment]
That's not how it works. You pass an object in and that object becomes the scope for the onTick method. As in, `this` is the object that you passed in.
