### ISSUE TITLE
Not working with Indian time zone

### ISSUE THREAD

**Issue by sijo-vijayan** [ncb000gt/node-cron#190]
Hi,

node-cron not working with Indian timezone, How can i fix it ? I want to run a cron job every month 'x' day 06:30:00 PM

 My code is given below.

		var CronJob = require('cron').CronJob;
		var job = new CronJob({
		  cronTime: '10 30 06 21 * 1-5',
		  onTick: function() {
			console.log('Done');
		  },
		  start: true,
		  timeZone: 'Asia/Mumbai'
		});
		job.start();

Please help me.
Thanks

**Comment by satyadeepk** [comment]
You will need to use `Asia/Kolkata` for Indian timezone.
All accepted timezones can be seen here, http://momentjs.com/timezone/

**Comment by ncb000gt** [comment]
Thanks @satyadeepk

**Comment by rolandoasmat** [comment]
This should be part of the README, had to dig in order to find a list of accepted timezones.
