### ISSUE TITLE
Does the cron process run on child process?

### ISSUE THREAD

**Issue by richacker** [ncb000gt/node-cron#192]
I printed the process.pid in the onTick event and one in normal application, both printed the same process id. Does the cron run on the main thread instead of child process?

**Comment by ncb000gt** [comment]
Cron runs in the same process as whatever you start it with. Although this isn't a bad idea, running in a child process, this project originated as a tool for the browser and so I kept that initially.

**Comment by citosid** [comment]
Since time has passed. Do you know if there is any way to do this in a different thread? Node now has [Cluster][1] as part of its API. 

Thank you for this awesome tool.

[1]: https://nodejs.org/api/cluster.html

**Comment by citosid** [comment]
We ended up using this:

https://docs.nestjs.com/microservices

We create several microservices with cluster and the do the communication via sockets.

**Comment by ncb000gt** [comment]
Ahh, cool. Glad you've found a solution. And, sorry about the delayed response. GL with the project!
