### ISSUE TITLE
Adding events and cron management

### ISSUE THREAD

**Issue by evanshortiss** [ncb000gt/node-cron#193]
Hey @ncb000gt,

Would you have any interest in accepting a PR that adds some management capabilities?

I've written a ["cron-master" module](https://github.com/evanshortiss/node-cron-master) that adds some neat features and helps enforce better management of cron jobs in a codebase, adds events, and prevents a cron instances from performing concurrent ticks. It could possibly be added to this module, but also works fine separately. It's a little opinionated perhaps.

**Comment by ncb000gt** [comment]
I guess it would depend on what you are talking about. That said, I've been fairly inactive on this project for a while because I don't have a lot of free time. So, I'm more likely to accept PR's than decline them unless I don't like the direction. :)

**Comment by evanshortiss** [comment]
Probably best to keep these separate for now. Thanks for the feedback
