### ISSUE TITLE
runOnInit doesn't work

### ISSUE THREAD

**Issue by PavelPolyakov** [ncb000gt/node-cron#201]
Here is the code:
```javascript
'use strict';

const CronJob = require('cron').CronJob;
const moment = require('moment');

let job = new CronJob({
    cronTime: '0 * * * * *',
    onTick: () => {
        console.log(`job 1`, `[${moment().format('YYYY-MM-DD HH:mm:ss')}]`);
    },
    start: true,
    runOnInit: true
});

console.log('Job was installed');
```

Here is the output:
![image](https://cloud.githubusercontent.com/assets/839290/11439752/befa8f74-94fd-11e5-976a-156b3587da43.png)

To test you need to do:
```
npm i moment
npm i cron
```

What I expect:
Job is executed right after the initialisation.

**Comment by jbach** [comment]
Doesn’t work for me either?

**Comment by PavelPolyakov** [comment]
I don't even find the ```runOnInit``` code piece in the source codes of the library.

**Comment by jbach** [comment]
For some reason Github doesn’t find this line: https://github.com/ncb000gt/node-cron/blob/master/lib/cron.js#L369

**Comment by PavelPolyakov** [comment]
I was trying to find it in the local lib.
And it is not there for sure.

Probably the current version of the library, with ```runOnInit```, is not published to npm.

**Comment by jbach** [comment]
You are right, seems like anything since this commit https://github.com/ncb000gt/node-cron/commit/487ccab8583322395028abe854e7d6d1f8ed7387 has not been published on npm.

**Comment by ncb000gt** [comment]
Sorry, I published the latest version. I had a few things I wanted to clean up but then forgot to push a new version with this change.

Take a look at the latest in npm. Thanks!

**Comment by PavelPolyakov** [comment]
thanks
