### ISSUE TITLE
i have a problem when use loop to create cron

### ISSUE THREAD

**Issue by kira8565** [ncb000gt/node-cron#207]
1、
var CronJob = require('cron').CronJob;
for (var i = 0; i < 2; i++) {
new CronJob('* * * * * *', consoleLog(i), null, true, 'America/Los_Angeles');
}
function consoleLog(i) {
console.log(i);
}

when i run this code ,the job run only once and will not continute

2、
var CronJob = require('cron').CronJob;
for (var i = 0; i < 2; i++) {
new CronJob('* * * * * *', function () {
console.log(i);
}, null, true, 'America/Los_Angeles');
}

when i run the code above ,i get 
2
2 
rather than 
0
1

**Comment by cadrogui** [comment]
Hi, did you try a pool of resources?, like generic-pool.

regards.

**Comment by kira8565** [comment]
I Only Use it in a simple loop,because I want to create multi cron job

**Comment by cadrogui** [comment]
here is an implementation with pooled resources:

````
var CronJob = require('node-cron').CronJob;
var poolModule = require('generic-pool');

var pool = poolModule.Pool({
  name     : 'PooledJobs',
  create   : function(callback) {
    // var yourClass = new yourClass();
    // callback(null, yourClass);
    callback(null, null)
  },
  destroy  : function(job) {
    console.log(job);
  },
  max      : 10000000,
  min      : 1,
  idleTimeoutMillis : 300000,
  log : false
});

var counter = 0;

function createJobs(period){
  new CronJob(period, function() {
    console.log(counter++)
    console.log('pool size', pool.getPoolSize());
  }, null, true, 'America/Santiago');
}

for(var i = 0; i < 20; i++){
  pool.acquire(function(err, yourClass){
    if(!err){
      createJobs('* * * * * *')
    }
  })
}
````

here is with no pool
````
var CronJob = require('node-cron').CronJob;
var counter = 0;

function createJobs(period, id){
  new CronJob(period, function() {
    console.log(counter++, id)
  }, null, true, 'America/Santiago');
}

for(var i = 0; i < 20; i++){
  createJobs('* * * * * *', 'job_id_' + i);
}
````

regards.

**Comment by kira8565** [comment]
It work ,Thank you  ヾ(=^▽^=)ノ
