### ISSUE TITLE
Cronjob not running when restart app or server

### ISSUE THREAD

**Issue by dinhquydcn92** [ncb000gt/node-cron#216]
I have Cronjob 
  var hello = function( ) {
      console.log('Hello world')
    }
    var job=new CronJob({cronTime:'00 52 13 * * *',

        // that's important (100% made up example):
        onTick: function() {
            hello({
                done: true,
                lastRun: new Date()
            });
        },

        start:false,timeZone:"America/Los_Angeles"});
    job.start();
when I restart server .Cronjob not running.

**Comment by klinquist** [comment]
This module does not persist cron jobs in any way.   When you schedule a new cron job, I recommend serializing the data to disk or a cache like redis... and simply read that data and re-schedule on startup.

**Comment by ncb000gt** [comment]
What @klinquist said. Thanks!

**Comment by cuong1181998** [comment]
nice @kkirsche
