### ISSUE TITLE
I would like to differentiate my jobs, so I can Identify the cron that is being executed.

### ISSUE THREAD

**Issue by methane47** [ncb000gt/node-cron#221]
Currently I'm storing a Job Name in the Timezone field of the Cronjob. But ofcourse this is a work around and not ideal.

In the Job element, are there any fields I can use as a job name?
So that I can print for example console.log(this.label);

**Comment by klinquist** [comment]
You can store anything you want in the optional _context_ object.


Sample code:
```
            var myJob = new cronJob({
                cronTime: "0 3 * * * *",
                onTick: cronFired,
                start: true,
                timeZone: "America/Los_Angeles",
                context: { jobName: "bob's cron" }
            });


function cronFired(){
   console.log(this.jobName);
}

```

**Comment by methane47** [comment]
Hey thanks for the assist. Its kinda wonky, in console logs if I print job[x].jobName i get undefined. but job[x].context.jobName prints correctly 

But at the same time this.jobName works while this.context.jobName doesn't
Anyways
Final code looks like this and it works

jobs[jobCounter] = new CronJob(jobTime, function(){addDocuments(this.jobName);}, null, true, null,{jobName: name});
