### ISSUE TITLE
0 * * * * * execute several times each millisecond

### ISSUE THREAD

**Issue by ysilvela** [ncb000gt/node-cron#234]
I supouse that only execute one time.

**Comment by GJ2511** [comment]
I think 0 0 0 0 0 0 is what you need

**Comment by ncb000gt** [comment]
If you only want one execution you can pass in a `Date` object. Otherwise, you'll want to use what @GJ2511 suggested. `0 * * * * *` will execute every minute of every hour of every day of every month of every year.
