### ISSUE TITLE
onTick fires several times even though cron time is set to every 10 minutes  

### ISSUE THREAD

**Issue by UndergroundLabs** [ncb000gt/node-cron#235]
I have the following set to run every 10 minutes.

The first problem is it fires every minute. The second problem is `onTick` fires several times.

```
import {CronJob} from 'cron'

new CronJob({
  cronTime: "* */10 * * * *",
  onTick: () => {
    console.log('Started');
  },
  start: true,
  timeZone: "Europe/London"
});
```

**Comment by canastro** [comment]
I'm having the same issue!

**Comment by GJ2511** [comment]
@UndergroundLabs  @canastro 

`cronTime: "* */10 * * * *"`
This means execute job after 10 min first time and then execute every second

You probably wants this
`cronTime: "0 */10 * * * *"`
