### ISSUE TITLE
Execute cron on last day of every month

### ISSUE THREAD

**Issue by nagainfosolutions** [ncb000gt/node-cron#240]
Hi,
I couldn't find out any solution for execute cron on last day of every month. 
Kindly help me to achieve this :)

**Comment by ultimate-tester** [comment]
0 0 3 L * ?

**Comment by ultimate-tester** [comment]
Duplicate of #210

**Comment by ncb000gt** [comment]
Closing as it's a duplicate. Please see linked ticket.
