### ISSUE TITLE
step value issue

### ISSUE THREAD

**Issue by manlok1992** [ncb000gt/node-cron#247]
I want to ask a stupid question. I am implement a function. This function will call on next next Sunday.
But I don't know how to write a step value in cron

**Comment by ncb000gt** [comment]
Right now we don't allow specific weekdays to be run. It may be a feature in the future to say something like "run X on the second sunday of the month".

If you just want something run every other sunday then you'll likely need to use something like: `0 0 0 0 7/2` (but I'm doing that off the top of my head, not certain that will work but you can probably find the syntax elsewhere on the web).
