### ISSUE TITLE
Parameters wrong

### ISSUE THREAD

**Issue by csimpi** [ncb000gt/node-cron#252]
Hi!
I would like to use cron inside a for loop.
The arguments wrong because i can't pass arguments to  ontick function.

```
    var TASKS = {1:{id:1,cron:'*/5 * * * * *',text:'Takarítás'},2:{id:2,cron:'*/10 * * * * *',text:'Kuka ürítés'}}
    for(k in TASKS){
        console.log('K outside',k);
        new CronJob(TASKS[k].cron, function() {
                this.stop();
                console.log('K inside',k);
                console.log(TASKS[k]);
        }, null, true, 'America/Los_Angeles');
    }
```

If i try to use this, i can get only the last element of array inside ontick:
K outside 1
K outside 2

K inside 2
{ id: 2, cron: '*/10 * * * * *', text: 'Kuka ürítés' }

K inside 2
{ id: 2, cron: '*/10 * * * * *', text: 'Kuka ürítés' }

**Comment by ncb000gt** [comment]
This isn't a cron issue, this is an issue with the way you setup your example. Look into closures specifically.
