### ISSUE TITLE
Out of sync timing information?

### ISSUE THREAD

**Issue by scheung38** [ncb000gt/node-cron#255]
var CronJob = require('cron').CronJob;

// Every 10 second regardless of time
new CronJob('10 * * * * *', function () {
    console.log('You will see this message every 10 second');
}, null, true, 'America/Los_Angeles');

But after 3 mins I got
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second

But I was expecting after first minute :
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second

and expecting after second minute :
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second

and expecting after third minute :
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second
You will see this message every 10 second

This test for every 5 seconds

new CronJob('5 * * * * *', function () {
    console.log('You will see this message every 5 second');
}, null, true, 'America/Los_Angeles');

You will see this message every 5 second appeared 45 seconds later instead of 5 seconds???

So only this works, for every second

new CronJob('* * * * * *', function () {
    console.log('You will see this message every second');
}, null, true, 'America/Los_Angeles');

**Comment by fetherolfjd** [comment]
The timing string of ```10 * * * * *``` is saying to run on the tenth second of every minute. To run something every 10 seconds you'd need ```*/10 * * * * *```.

**Comment by ncb000gt** [comment]
What @fetherolfjd said is true. Also, rather than printing "see this in 10 seconds" you should print `new Date().toString()` to get a much more accurate picture of when the onTick is firing.

Closing since this is an issue with the syntax.
